on:
- push

jobs:
  build:
    strategy:
      matrix:
        os:
        - macOS-latest
        - ubuntu-20.04
        - windows-2019
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies (Linux)
      if: startsWith(matrix.os, "ubuntu-")
      run: sudo apt install libpcap-dev
    - run: swift run